version: '3.8'

services:
  web-prod:
    container_name: driving-license-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file: .env.production
    ports:
      - '3000:3000'
    restart: always
