version: '3.8'

services:
  license-fe:
    container_name: license-prod
    build:
      context: .
      dockerfile: Dockerfile
      image: license-fe-prod
    environment:
      - NODE_ENV=production
    env_file: .env.production
    ports:
      - '3000:3000'
    restart: always
