version: '3.8'

services:
  license-fe:
    container_name: license-test
    build:
      context: .
      dockerfile: Dockerfile
    image: license-fe-test
    environment:
      - NODE_ENV=test
    env_file: .env.test
    ports:
      - '2000:3000'
    restart: always
