version: '3.8'

services:
  web-test:
    container_name: driving-license-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    env_file: .env.test
    ports:
      - '2000:3000'
    restart: always
